spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Mexico_City
    locale: es_MX    
    serialization:
      fail-on-empty-beans: false
  profiles: 
    active: local
  datasource:
    url: ${CADENA_CONEXION_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Mexico_City
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  
server:
  servlet:
    contextPath: /mssppa-catalogos/v1
  port: 8080

logging:
  file:
    name: mssppa-catalogos.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    '[org.hibernate.sql]': ${LOG_LEVEL}
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE 
    '[org.springframework]': INFO
    '[mx.gob.imss.cit.sppa.catalogos]': ${LOG_LEVEL}
management:
  endpoints:
    web:
      base-path: /msmjlssc-administracion/actuator
      exposure:
        include: health, info, env, beans, metrics, threaddump, vigencia, genericEndPoints
  endpoint:
    health:
      show-details: always
    security:
      enabled: false
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    git:
      mode: full